    name: Generate device tree
      run: |
        # 尝试标准方法
        python3 -m twrpdtgen -o dt/ *.img || echo "自动生成失败，使用手动方法"
        
        # 检查是否生成成功
        if [ ! -f "dt/Android.mk" ] && [ ! -f "dt/omni_PCDM10.mk" ]; then
          echo "创建手动设备树..."
          mkdir -p dt/oppo/PCDM10
          
          # 使用 base64 编码内容来避免 YAML 解析问题
          base64 -d << EOF > dt/oppo/PCDM10/Android.mk
TE9DQUxfUEFUSCA6PSAkKGNhbGwgbXktZGlyKQoKKGNhbGwgaW5oZXJpdC1wcm9kdWN0LCB2ZW5kb3Iv
b21uaS9jb25maWcvc3NtLm1rKQooY2FsbCBpbmhlcml0LXByb2R1Y3QsICQoTE9DQUxfUEFUSCkvZGV2
aWNlLm1rKQoKKGNhbGwgaW5oZXJpdC1wcm9kdWN0LCB2ZW5kb3Ivb21uaS9jb25maWcvY29tbW9uLm1r
KQoKUFJPRFVDVF9ERVZJQ0UgOj0gUENETTEwClBST0RVQ1RfTkFNRSA6PSBvbW5pX1BDRE0xMApQUk9E
VUNUX0JSQU5EIDo9IE9QUE8KUFJPRFVDVF9NT0RFbCA6PSBSZW5vIFoKUFJPRFVDVF9NQU5VRkFDVFVS
RVIgOj0gT1BQTw==
EOF

          base64 -d << EOF > dt/oppo/PCDM10/device.mk
TE9DQUxfUEFUSCA6PSAkKGNhbGwgbXktZGlyKQoKKGNhbGwgaW5oZXJpdC1wcm9kdWN0LCAkKFNSQ19U
QVJHRVRfRElSKSSwcm9kdWN0L2Z1bGxfYmFzZS5taykKClBST0RVQ1RfTkFNRSA6PSBQQ0RNMTAKUFJP
RFVDVF9CUkFORCA6PSBPUFBPClBST0RVQ1RfTU9ERUwgOj0gUmVubyBaClBST0RVQ1RfTUFOVUZBQ1RV
UkVSIDo9IE9QUE8KUFJPRFVDVF9ERVZJQ0UgOj0gUENETTEw
EOF

          base64 -d << EOF > dt/oppo/PCDM10/BoardConfig.mk
VEFSR0VUX05PX0tFUk5FTCA6PSB0cnVlCkJPQVJEX0tFUk5FTF9DTURMSU5FIDo9IGNvbnNvbGU9dHR5
TVNNMCwxMTUyMDBuOCBhbmRyb2lkYm9vdC5oYXJkd2FyZT1xY29tCkJPQVJEX0tFUk5FTF9CQVNFIDo9
IDB4ODAwMDAwMDAKQk9BUkRfS0VSTkVMX1BBR0VTSVpFIDo9IDQwOTYKQk9BUkRfS0VSTkVMX09GRlNF
VCA6PSAweDAwMDA4MDAwCkJPQVJEX1JBWURJU0tfT0ZGU0VUIDo9IDB4MDEwMDAwMDAKQk9BUkRfVEFH
U19PRkZTRVQgOj0gMHgwMDAwMDEwMA==
EOF

          echo 'add_lunch_combo omni_PCDM10-eng' > dt/oppo/PCDM10/vendorsetup.sh
          echo 'add_lunch_combo omni_PCDM10-userdebug' >> dt/oppo/PCDM10/vendorsetup.sh
          
          base64 -d << EOF > dt/oppo/PCDM10/omni_PCDM10.mk
KGNhbGwgaW5oZXJpdC1wcm9kdWN0LCBkZXZpY2Uvb3Bwby9QQ0RNMTAvZGV2aWNlLm1rKQoKUFJPRFVD
VF9OQU1FIDo9IG9tbmlfUENETTEw
EOF
        fi
